version: 0.0
os: linux
files:
  - source: ./backend/application.py
    destination: /var/www/sample-app
  - source: /
    destination: /home/ec2-user/sample-app
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
