version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - pip install -r requirements.txt
      - docker login --username smohammed714 --password, -p System123*
  build:
    commands:
      - ls -al
      - docker version
      - docker image build -t anagram-714:latest 
      - docker tag anagram-714:latest smohammed714/anagram-714:latest
  post_build:
    commands:
      - docker push smohammed714/anagram-714:latest
