version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - pip install -r requirements.txt
      - docker login --username adilforms --password $PASSWORD
  build:
    commands:
      - ls -al
      - docker image build -tag adilforms/anagram-final:latest .
  post_build:
    commands:
      - docker push adilforms/anagram-final:latest
